name = "SearchSortedNearest"
uuid = "e8f3a9d7-1e19-435f-864b-2435d14e4e17"
authors = ["joshday <emailjoshday@gmail.com> and contributors"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
